[package]
name = "ci-cd"
version = "0.1.0"
edition = "2021"
authors = ["Dang Quang Vu <eamondang@gmail.com>"]
repository = "https://github.com/eamondang/rust-initial.git"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
